MongoSh1Rs1:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm && mongod --replSet rs1  --dbpath /mmm --storageEngine wiredTiger"'
MongoSh1Rs2:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm && mongod --replSet rs1  --dbpath /mmm --storageEngine wiredTiger"'
MongoSh1Rs3:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm && mongod --replSet rs1  --dbpath /mmm --storageEngine wiredTiger"'
MongoSh2Rs1:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm && mongod --replSet rs2  --dbpath /mmm --storageEngine wiredTiger"'
MongoSh2Rs2:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm && mongod --replSet rs2  --dbpath /mmm --storageEngine wiredTiger"'
MongoSh2Rs3:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm && mongod --replSet rs2  --dbpath /mmm --storageEngine wiredTiger"'
MongoConfigsvr1:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm/configdb && mongod --configsvr --dbpath /mmm --replSet configReplSet --port 27019 --storageEngine wiredTiger"'
MongoConfigsvr2:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm/configdb && mongod --configsvr  --dbpath /mmm --replSet configReplSet --port 27019 --storageEngine wiredTiger"'
MongoConfigsvr3:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mkdir -p /mmm/configdb && mongod --configsvr  --dbpath /mmm --replSet configReplSet --port 27019 --storageEngine wiredTiger"'
MongoRouter:
  image: docker.iwanna.xyz:5000/mongo
  command: '/bin/bash -c "mongo {{MongoConfigsvr1}}:27017/config --eval \"printjson(rs.initiate({_id: \\\"configReplSet\\\",configsvr:true,members:[{_id: 0, host:\\\"{{MongoConfigsvr1}}:27019\\\"},{_id: 1, host: \\\"{{MongoConfigsvr2}}:27019\\\"},{_id: 2, host: \\\"{{MongoConfigsvr3}}:27019\\\"}]}))\" && mongos --configdb configReplSet/{{MongoConfigsvr1}}:27019,{{MongoConfigsvr2}}:27019,{{MongoConfigsvr3}}:27019"'
  links:
    - MongoConfigsvr3
    - MongoConfigsvr2
    - MongoConfigsvr1
